I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    serg "привет"
Exception: Sayer 'serg' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script
    serg "привет"
  File "D:\Serg\programm\rpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 615, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Serg\programm\rpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 528, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'serg' is not defined.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
first 1.0
Thu Mar 01 00:12:16 2018
